project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Notes"

  page-footer:
    center: "Page built with [Quarto](https://quarto.org/)."
  navbar:
    background: $body-bg
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme:
      light: [default, theme-light.scss]
      dark: [cyborg, theme-dark.scss]
    css: style.css
    code-copy: true
    code-overflow: wrap
    toc: true
    code-fold: true
    code-tools: true
    html-math-method: katex
    include-in-header:
      text: |
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap" rel="stylesheet">
    linestretch: 1
    mainfont: Nunito
jupyter: python3
execute:
  warning: false