#!/bin/bash

PASSWORD=$1

# If no password is provided, read it from the .env file
if [ -z "$PASSWORD" ]; then
    if [ ! -f .env ]; then
        echo "No password provided and .env file does not exist."
        exit 1
    fi
    export $(grep -v '^#' .env | xargs)
    PASSWORD=$DEFAULTPSW
fi

# Go to the encrypted directory
cd encrypted || exit 1

# Decrypt each file
for file in *.enc; do
    # Decrypt the file to a temporary file
    openssl enc -aes-256-cbc -pbkdf2 -d -salt -in "$file" -out tmp_file -k "$PASSWORD"

    # Read the first line to get the original filename
    original_filename=$(head -n 1 tmp_file)

    # Remove the first line from the temporary file and save it as the original file
    tail -n +2 tmp_file > "../$original_filename"

done

# Remove temporary file
rm tmp_file

